services:
  # PostgreSQL - Main database
  postgres:
    image: postgres:15-alpine
    container_name: piper-postgres
    environment:
      POSTGRES_DB: piper_morgan
      POSTGRES_USER: piper
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_changeme}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piper"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - Cache and event queue
  redis:
    image: redis:7-alpine
    container_name: piper-redis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChromaDB - Vector database
  chromadb:
    image: chromadb/chroma:latest
    container_name: piper-chromadb
    volumes:
      - ./data/chromadb:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      ANONYMIZED_TELEMETRY: "false"
      ALLOW_RESET: "true"

  # Temporal - Workflow orchestration (FIXED)
  temporal:
    image: temporalio/auto-setup:latest
    container_name: piper-temporal
    ports:
      - "7233:7233"
      - "8088:8088"
    environment:
      - DB=postgres12  # Fixed: needs to be postgres12, not postgres
      - DB_PORT=5432
      - POSTGRES_USER=piper
      - POSTGRES_PWD=${POSTGRES_PASSWORD:-dev_changeme}
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=piper_morgan
    depends_on:
      postgres:
        condition: service_healthy

  # Traefik - API Gateway (minimal config)
  traefik:
    image: traefik:v3.0
    container_name: piper-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: piper-network
